# IDF v5.3; ESP8266@; ESP32@  — CI test image (amd64)
FROM --platform=linux/amd64 debian:13.5-slim

LABEL version="1.8.96"

ENV DEBIAN_FRONTEND=noninteractive
ENV ESP_IDF_VERSION="v5.3"

RUN mkdir /opt/workspace
WORKDIR /opt/workspace
COPY cmd.sh /opt/

COPY dummy-esp8266 /opt/dummy-esp8266
COPY dummy-esp32 /opt/dummy-esp32
COPY dummy-esp32-idf /opt/dummy-esp32-idf
COPY tests /opt/tests
RUN chmod +x /opt/tests/*.sh

RUN apt update -qq && \
apt install -y -qq --no-install-recommends software-properties-common gpgv2 && \
apt install -qq -y --no-install-recommends \
bc \
bison \
build-essential \
ccache \
cmake \
curl \
dfu-util \
flex \
gcc \
git \
gperf \
jq \
libffi-dev \
libncurses-dev \
libssl-dev \
libusb-1.0-0 \
make \
ninja-build \
python3 \
python3-dev \
python3-pip \
python3-venv \
srecord \
unzip \
wget \
xz-utils \
&& apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#
# Install Python components
#

RUN python3 -m pip install --break-system-packages pipx setuptools platformio virtualenv intelhex
RUN python3 -m pipx ensurepath
RUN python3 -V

#
# ESP32 & ESP8266 Arduino Frameworks for Platformio
#

RUN pio platform install espressif8266 \
 && pio platform install espressif32 \
 && chmod 777 /root/.platformio/platforms/espressif32/platform.py \
 && sed -i 's/~2/>=1/g' /root/.platformio/platforms/espressif32/platform.py

#
# ESP-IDF for projects containing `sdkconfig` or `*platform*espidf*` in platformio.ini
#

RUN mkdir -p ~/esp \
 && cd ~/esp \
 && git clone -b ${ESP_IDF_VERSION} --recursive https://github.com/espressif/esp-idf.git
RUN cd ~/esp/esp-idf \
 && ./install.sh all

CMD /opt/cmd.sh
